### PR TITLE
Fix failing tests and unify testsuite

### LINKED ISSUE #34: Fix failing tests
`make test` fails currently.

We may also want to bring in a testing library (https://github.com/stretchr/testify).

`OutputFormat` should use the generic test suite

### PR DESCRIPTION
**Pull request by RRethy**
Fix #34 

With OutputFormat being added to commands, the version tests started failing. I also wanted to reuse the logic from `cmd/test/test.go` for the OutputFormat tests, so I brought it under `pkg/cli/testsuite` and made it a bit more minimal (we can increase it's features as we build out more commands).

I also brought in https://github.com/stretchr/testify for testing to use it mainly as an assertion library.

### CODE REVIEW

**Comment by voigt** [comment]
About testify: the chat was more or less uni soon that "go test should be enough. I, for one, appreciate the use of testify assertions. However, I understand that it's quite a big dependency for just using assertions. Maybe @krisnova / @dmah42 have opinions?

**Comment by voigt** [comment]
Also +1 for "human readable" as default output.

**Comment by RRethy** [comment]
> About testify: [the chat](https://discord.com/channels/1026578122969206796/1026613433220726834/1061408339713605692) was more or less uni sono that "go test should be enough. Therefore I intentionally built the first test without testify.

Good to know. I'll update the PR.

> Also +1 for "human readable" as default output.
https://discord.com/channels/1026578122969206796/1026613433220726834/1062503346226876446

What are your thoughts on not using `--output` for stuff like that (and using it only for structured output) and creating a logger interface for things like screenshot you posted in discord?

With `kubectl`, if you do a command like `kubectl get -v 6` you'll get structured output determined by `--output` along with additional logging output which is ignorant to `--output`.

**Comment by voigt** [comment]
> With kubectl, if you do a command like kubectl get -v 6 you'll get structured output determined by --output along with additional logging output which is ignorant to --output.
> 
> Edit: We could even just skip the logger and use fmt directly for unstructured output since we have your SetWriter code.

I agree. I think it will add benefit to add a logger.
Yes, we could start with fmt directly. However, whats wrong with directly go with a structured logger that is aware of loglevels?

**Comment by RRethy** [comment]
> > With kubectl, if you do a command like kubectl get -v 6 you'll get structured output determined by --output along with additional logging output which is ignorant to --output.
> > Edit: We could even just skip the logger and use fmt directly for unstructured output since we have your SetWriter code.
> 
> I agree. I think it will add benefit to add a logger. Yes, we could start with fmt directly. However, whats wrong with directly go with a structured logger that is aware of loglevels?

I'm good with that too.

**Comment by krisnova** [comment]
Bump. Can we resolve these conflicts and get this merged? Looks like we are in a good spot. Do we have any blockers right now?

**Comment by RRethy** [comment]
This is rebased and ready for merge.

File: cmd/version/version.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func (o *option) SetWriter(writer io.Writer) {
 func NewCMD() *cobra.Command {
 	o := &option{
 		outputFormat: cli.NewOutputFormat().
-			WithDefaultFormat(printer.NewJSON().Format()).
+			WithDefaultFormat(printer.NewYAML().Format()).
```
Comment (dmah42) [inline cmd/version/version.go:86]: why is this changing the default to yaml?

Comment (RRethy) [reply cmd/version/version.go:86]: At the time of writing the PR originally, the test was checking for YAML output since that's what was being used ([commit](https://github.com/aurae-runtime/ae/commit/cd721228387bb8ddc3e2889ddf63b0a0e1bef75b#diff-a6e9cedf36ae1f9b807d361a421ec6a917637b9e11630fde62ded50f8b547d85R46-R52) ), then the the OutputFormat PR changed it to JSON which broke the test. This change was just to keep the tests the same and yaml did seem more natural for output from a `version` command. I can change it back to json if you want, I'm good with either.

Comment (dmah42) [reply cmd/version/version.go:86]: yes please. our README suggests we should be moving towards JSON as output across the board. earlier flexibility to allow yaml was useful but not something we want to maintain going forward.

Comment (RRethy) [reply cmd/version/version.go]: Updated 👍

**Review by dmah42 — APPROVED** [review]
